### ISSUE TITLE
For eclipse

### ISSUE THREAD

**Issue by prasad456** [Yalantis/Context-Menu.Android#10]
I want same as in eclipse

**Comment by alexzaitsev** [comment]
You can download the source and import it as library project

**Comment by prasad456** [comment]
Lots of error like
Appcombat, R.java, etc.,




Thanks and Regards


Durga Venkat Prasad. ViGiNiGiRi.
Android Application Developer
*Ebiz Solutions*
Phone: (513)-342-2772 (VOIP)
          +91 4064515658 (Office)
          +91 9030268916 (Mobile)



On Mon, Mar 23, 2015 at 2:58 PM, Alexander Zaitsev <notifications@github.com

**Comment by alexzaitsev** [comment]
I don't use Eclipse so cannot help you. Maybe it is a good time to start using Android Studio
