### ISSUE TITLE
Option to close menu when user touches the darkened area.

### ISSUE THREAD

**Issue by graphnode** [Yalantis/Context-Menu.Android#13]
There should be an option to close the menu when the user touches the darkened area since that is the usual behavior for interfaces like this.

An option should be added with the default value of false to keep backwards compatibility.

**Comment by Apisov** [comment]
Yeah, sounds good. We'll add this ASAP.

**Comment by alexzaitsev** [comment]
Done. Thank you for participation. Feel free to make pull requests in future.

**Comment by Oliveira1** [comment]
Thanks !
