### ISSUE TITLE
Setting Divider Transparent Not Working

### ISSUE THREAD

**Issue by matthewrice345** [Yalantis/Context-Menu.Android#14]
MenuObject.setDividerColor(Color.TRANSPARENT);

When setting transparent the color ends up white.

**Comment by Apisov** [comment]
But another colors works fine? Could it be that layout below menu is white?

**Comment by alexzaitsev** [comment]
Merged. Thank you for participation.

**Comment by stefannew** [comment]
I'm still having the same issue when trying to set divider colors and background colors to transparent.
