### ISSUE TITLE
Context menu is openening second time on clicking a button on actionbar

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [Yalantis/Context-Menu.Android#17]
Getting following error when clicking on button to open context menu

Could not find method android.widget.RelativeLayout.setBackground, referenced from method com.yalantis.contextmenu.lib.Utils.getImageWrapper

**Comment by alexzaitsev** [comment]
Fixed. For now changes are in the `develop` branch. You can use this fix by yourself in the Utils.java

com.yalantis.contextmenu.lib.Utils.getImageWrapper(...):

```
            if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.JELLY_BEAN) {
                imageWrapper.setBackgroundDrawable(menuItem.getBgDrawable());
            } else {
                imageWrapper.setBackground(menuItem.getBgDrawable());
            }
```
