### ISSUE TITLE
setAnimationDuration doesn´t work for open event 

### ISSUE THREAD

**Issue by juancabeco** [Yalantis/Context-Menu.Android#22]
Hi, great job but i found a bug.
When you set a setAnimationDuration it only apply to close event.

The reason is because MenuAdapter constructor is setting the mAnimationDurationMilis default (100) before the setAnimationDuration has called

;-)

**Comment by alexzaitsev** [comment]
Hi, thank you very much, I'll check it.

**Comment by alexzaitsev** [comment]
Fixed in new `1.0.5` version. Commit: https://github.com/Yalantis/Context-Menu.Android/commit/b3e48a969b6e23823e622f1c7a1508b655f9ffb6
You can find `changelog` in the `readme`: https://github.com/Yalantis/Context-Menu.Android/blob/master/README.md
