### ISSUE TITLE
implements in Fragment

### ISSUE THREAD

**Issue by laurence-liu** [Yalantis/Context-Menu.Android#24]
Hi, it is really an awesome animated context menu!!
Thanks!!
But is it possible to implements OnMenuItemClickListener / OnMenuItemLongClickListener in Fragment?

**Comment by kamilwlf** [comment]
I wonder why it does not work

**Comment by alexzaitsev** [comment]
Fixed in new `1.0.5` version. Commit: https://github.com/Yalantis/Context-Menu.Android/commit/dc4c4f9a09e7c9aca51aae789f726eeab7db59d8
You can find `changelog` in the `readme`: https://github.com/Yalantis/Context-Menu.Android/blob/master/README.md
