### ISSUE TITLE
setClosableOutside destroy the current activity 

### ISSUE THREAD

**Issue by nowfalsalahudeen** [Yalantis/Context-Menu.Android#25]
setClosableOutside close the current activity when touch the non button area and go back to the previous activity.. please take a look

**Comment by kamilwlf** [comment]
I have the same problem, how to solve it?

**Comment by kamilwlf** [comment]
try this:
@Override
            public void onBackPressed() {
                if (mMenuDialogFragment != null && mMenuDialogFragment.isAdded()) {
                    mMenuDialogFragment.dismiss();
                } else{
                    finish();
                }
            }

**Comment by alexzaitsev** [comment]
@nowfalsalahudeen @kamilwlf of course I can fix this issue with View.OnKeyListener in dialog fragment. But in this case you as users of library have less flexibility. So you have to override `onBackPressed`. Thank you for question and answer, I'll add this to readme.

**Comment by alexzaitsev** [comment]
Fixed in new `1.0.5` version. 
https://github.com/Yalantis/Context-Menu.Android/commit/ca09b4786e34a617e927b85c54bc8068f1a33e46
You can find `changelog` in the `readme`: https://github.com/Yalantis/Context-Menu.Android/blob/master/README.md
