### ISSUE TITLE
Hi How can we make this menu come to left handside.

### ISSUE THREAD

**Issue by ashokslsk** [Yalantis/Context-Menu.Android#26]
Hi great job with this menu component but how do we make it come in left handside of the android device and one more question can we inflate view badger to the menu item if and when we have the notification let me know . Honestly great job Thank you

**Comment by alexzaitsev** [comment]
Hi, thank you for your kindness. 
If you are interested in this feature you can create a pull request. We react to the pull requests ASAP.
