### ISSUE TITLE
How to change the default White color of the Menu

### ISSUE THREAD

**Issue by sh0umik** [Yalantis/Context-Menu.Android#28]
I am searching for methods for changing the default White color of the Menu . Couldn't find one . Can you tell me how will i achieve this ?

**Comment by alexzaitsev** [comment]
Hi, all you need is to customize your `MenuObject` instances. Check `getMenuObjects()` method in the sample: https://github.com/Yalantis/Context-Menu.Android/blob/master/app/src/main/java/com/yalantis/contextmenu/sample/MainActivity.java#L54
