### ISSUE TITLE
How to use in my android project

### ISSUE THREAD

**Issue by dasbiswajit** [Yalantis/Context-Menu.Android#29]
Hi Man,
I am very new to Android development. I am not using gradle. Can you please let me know how to include in my project. 
1. When I clone your project to eclipse(Mars) it is showing the following structure- 

![context menu](https://cloud.githubusercontent.com/assets/3852746/11452442/9beb8afe-960d-11e5-9adb-01d41cafbe71.JPG)

2. my project structure is given below.

![my app](https://cloud.githubusercontent.com/assets/3852746/11452453/c66e9e2e-960d-11e5-825b-9fe64ca45ffd.JPG)

Now shall I copy the "lib" folder (lib\src\main\...) to my "src" folder?
Normally I add the library like the following way- 

![adding library](https://cloud.githubusercontent.com/assets/3852746/11452458/f8028c98-960d-11e5-87fa-7c11b653c82b.JPG)
Could you please help me here?

Regards
Biswajit Das

**Comment by PenzK** [comment]
Thank you for your interest but use google
