### ISSUE TITLE
How to call from button ?? 

### ISSUE THREAD

**Issue by klingofmonsterdev** [Yalantis/Context-Menu.Android#30]
I have call library from button without use Action Bar ??

**Comment by pawlo2102** [comment]
You need to call method  openOptionsMenu();

example :  
button.setOnClickListener(new OnClickListener() {
        public void onClick(View v) {
            openOptionsMenu();
        }
    });

**Comment by klingofmonsterdev** [comment]
Thank You.
I try to do it.

**Comment by alexzaitsev** [comment]
Closed as resolved.
