### ISSUE TITLE
Change background color of each item

### ISSUE THREAD

**Issue by deepakcipl** [Yalantis/Context-Menu.Android#33]
Hi Thanks for your wonderful tutorial.
I have 3 transparent images and want to set a background color of each item. How can I achieve that in your library ?

**Comment by deepakcipl** [comment]
Apart from this, I want to show menus center of layout. How can I acheive that ?

**Comment by PenzK** [comment]
To change color of menu item just use method setBgColor(int mBgColor) of MenuObject

**Comment by PenzK** [comment]
There is no ability to move menu items in library. Its open source so you can fork it and adopt to your needs.
