### ISSUE TITLE
double click will cause crash

### ISSUE THREAD

**Issue by likebamboo** [Yalantis/Context-Menu.Android#4]
when I double-click the menu button, the application will crash

**Comment by alexzaitsev** [comment]
Thank you. We will check it.

**Comment by alexzaitsev** [comment]
Please provide more details. Could you share your code?

**Comment by likebamboo** [comment]
I install the  Sample Apk .  
When I  double-click (very fast) the menu button in the upper right corner,  the application will crash .

**Comment by alexzaitsev** [comment]
Fixed. For now changes are pushed to develop branch.
