### ISSUE TITLE
onMenuItemClick - Another Activity 

### ISSUE THREAD

**Issue by TechTycoon** [Yalantis/Context-Menu.Android#46]
Hello PenzK and others, LOVE the Context Menu!! I read a previous issue #31 and having a similar issue with the onMenuItemClick, I cannot wrap my head around getting past why I cannot click on the menu item and go to another activity. I read the Check Block 5, but confused where I need to add this (going to use intent) for each menu item. Do I add in Main Activity or the ContextMenuDialogFragment? 

Penzk stated to set listeners to the context fragment manually and view Check Block 5 (see below). Where it states below, "...public void onMenuItemClick(View clickedView, int position) {
//Do something here" is this the area I should put my intents? 

From Github Check Block 5 it shows Main Activity below:

*\* Implement OnMenuItemClickListener interface with onMenuItemClick method.**

public class MainActivity extends ActionBarActivity implements OnMenuItemClickListener
…
@Override
public void onMenuItemClick(View clickedView, int position) {
//Do something here 
}
…
mMenuDialogFragment.setItemClickListener(this);

Any additional guidance is GREATLY appreciated. Thank you for your time.

**Comment by TechTycoon** [comment]
Update: I was able to get the MenuItem to somewhat work when I click on the MenuItem they go to another activity (see code onMenuItemClick below), BUT the issue is they do not go to the correct activity, they all go to the same one, what am I doing wrong? The XMLs file are the same, no changes. Also I want to remove the toasts altogether, what is the best way to do so? 

 }
    }
 @Override
    public void onMenuItemClick(View clickedView, int position) {

        action_fruit = (MenuItem) findViewById(R.id.action_fruit);
        Intent intent = new Intent(ABCActivity.this, Fruit.class);
        startActivity(intent);

        action_green= (MenuItem) findViewById(R.id.action_green);
        intent = new Intent(ABCActivity.this, Tea.class);
        startActivity(intent);

        action_drink = (MenuItem) findViewById(R.id.action_drink);
        intent = new Intent(ABCActivity.this, Coffee.class);
        startActivity(intent);

        action_post = (MenuItem) findViewById(R.id.action_post);
        intent = new Intent(ABCActivity.this, Drinks.class);
        startActivity(intent);

        action_home = (MenuItem) findViewById(R.id.action_home);
        intent = new Intent(ABCActivity.this, Home.class);
        startActivity(intent);

        Toast.makeText(this, "Clicked on position: " + position, Toast.LENGTH_SHORT);
        mMenuDialogFragment.setItemClickListener(this);
}

    @Override
    public boolean onMenuItemClick(MenuItem item) {
        return false;
    }

    @Override
    public void onMenuItemLongClick(View clickedView, int position) {
        Toast.makeText(this, "Long clicked on position: " + position, Toast.LENGTH_SHORT);
    }
}

Thank you kindly and all is appreciated!

**Comment by swetakadam** [comment]
Hi -- I got this menu click go to another activity  ..

  Intent document = new Intent(getActivity(),DocumentActivity.class);
            // set the document id which is suppose to be opened
            document.putExtra("document_id",openDocument.getId());
            document.putExtra("document_name",openDocument.getDocumentName());
            //start the activity
            startActivity(document);

What I see from your code  .. make sure you have deleted this part 
@Override
public boolean onMenuItemClick(MenuItem item) {
    return false;
}

if you keep this part  ... it will go back to same activity  ...

to remove toast  just comment it out 

//Toast.makeText(this, "Long clicked on position: " + position, Toast.LENGTH_SHORT);
return false if you don't want to support long click

**Comment by TechTycoon** [comment]
Hello swetakadam,

Thank YOU for your support. I've been trying to figure what you provided to my code for the last few days, but I am SOOO confused. The objective is to tap the button (see Github link below) and go to that button's activity https://github.com/Yalantis/Context-Menu.Android. I can do this no problem in onOptionsSelected, but this is a context menu which is new to me and there's the issue. 

When I use your code above, I'm not sure what I should put for "document_id",openDocument.getId()); and ("document_name",openDocument.getDocumentName());. 

Thank you swetakadam!!

**Comment by warko-san** [comment]
Hi, guys!
@TechTycoon If I clearly understood you, you want to go to some activity when tapping some button.
In your activity (like in the sample) you implement `onMenuItemClickListener()` and in the interface implementation you have two parameters passed - `clickedView` and `position`.
I assume, you can start your desired activity something like this:
`@Override
    public void onMenuItemClick(View clickedView, int position) {
        switch (position) {
            case 1:
                startActivity(new Intent(MainActivity.this, FruitActivity.class));
                break;
            case 2:
                startActivity(new Intent(MainActivity.this, TeaActivity.class));
                break;
               //And other your activities
        }
    }`
