### ISSUE TITLE
Not able to re-position the dialog.

### ISSUE THREAD

**Issue by jayuu26** [Yalantis/Context-Menu.Android#47]
Hi,
 I am not able to re-position the ContextDialogFragmnet.

 public void setDialogPosition(ContextMenuDialogFragment mMenuDialogFragment) {
        Window window = mMenuDialogFragment.getDialog().getWindow();
        window.setGravity(Gravity.BOTTOM | Gravity.LEFT);

```
    WindowManager.LayoutParams params = window.getAttributes();
    params.y = dpToPx(60);
    window.setAttributes(params);
}
```

Getting getDialog() is null.

Please let me know how to reposition this dialog  as i want to show this dialog along with my custom view or in Center of the screen.

Thanks in advance.

**Comment by joShinichi** [comment]
same problem with me too....

**Comment by PenzK** [comment]
For now library does not support direction change. But you can edit fragment_menu.xml and change position of containers. You can edit animation directions in MenuAdapter.class.
You are welcome to contribute
