### ISSUE TITLE
Change layout position

### ISSUE THREAD

**Issue by black-lotus** [Yalantis/Context-Menu.Android#48]
Hi, 
First of all thank you for making this awesome library, save my time :)
I have problem to customize the view :
how to change layout position, i need to set my image resource on center_horizontal and align to bottom

<img width="301" alt="screen shot 2016-10-29 at 5 40 40 pm" src="https://cloud.githubusercontent.com/assets/3261560/19828968/317f8ada-9dff-11e6-9638-b01059ba3649.png">

Thank you

**Comment by warko-san** [comment]
Hi, @black-lotus! Thank you for your issue. But, actually, you cannot do that, because all item images are considered to be at the centre. And there is no support to change their layout position.

**Comment by PenzK** [comment]
You can edit Utils.getImageWrapper(...) method and getItemImageButton(...)  to edit appearance of items
