### ISSUE TITLE
Open menu onLongClick

### ISSUE THREAD

**Issue by sagarrishabh** [Yalantis/Context-Menu.Android#49]
I wanted to know if I can open this context menu when I long press any item in recycler view?

**Comment by root1991** [comment]
Of corse you can, but you should implement OnItemLongClickListener for your recycler view. There are some examples: http://stackoverflow.com/questions/30078344/handle-on-item-long-click-on-recycler-view
Good luck!)

**Comment by sagarrishabh** [comment]
hey it worked, thanks a lot friend :)

**Comment by sagarrishabh** [comment]
hey I have a doubt... how can I know the position of an item that was clicked?

**Comment by sagarrishabh** [comment]
I figured out :)
