### ISSUE TITLE
How did u change the Icon on the ToolBar?

### ISSUE THREAD

**Issue by syedalinaqi** [Yalantis/Context-Menu.Android#5]
Can u please tell me how did u changed the oveflow menu icon.

**Comment by alexzaitsev** [comment]
If you mean menu icons, read the readme (step 2):

ArrayList<MenuObject> menuObjects = new ArrayList<>();
        menuObjects.add(new MenuObject(R.drawable.icn_close));
        menuObjects.add(new MenuObject(R.drawable.icn_1, "Send message"));
        menuObjects.add(new MenuObject(R.drawable.icn_2, "Like profile"));
        menuObjects.add(new MenuObject(R.drawable.icn_3, "Add to friends"));
        menuObjects.add(new MenuObject(R.drawable.icn_4, "Add to favorites"));
        menuObjects.add(new MenuObject(R.drawable.icn_5, "Block user"));

Actionbar/Toolbar menu icon totaly depends on your code and not on library.
Read documentation: http://developer.android.com/reference/android/support/v7/widget/Toolbar.html
In our example you can found icon setting here: https://github.com/Yalantis/Context-Menu.Android/blob/master/app/src/main/res/menu/menu_main.xml
Line: android:icon="@drawable/btn_add"
