### ISSUE TITLE
Fragment already added: ContextMenuDialogFragment

### ISSUE THREAD

**Issue by BaranBerk** [Yalantis/Context-Menu.Android#50]
We are getting this error any ideas?

Fatal Exception: java.lang.IllegalStateException
Fragment already added: ContextMenuDialogFragment{1e2785d #0 ContextMenuDialogFragment}

**Comment by warko-san** [comment]
Hi, @BaranBerk! Can you please provide your code, where you are getting this exception?

**Comment by BaranBerk** [comment]
FragmentManager.java line 1357
android.support.v4.app.FragmentManagerImpl.addFragment

Fatal Exception: java.lang.IllegalStateException
Fragment already added: ContextMenuDialogFragment{10490376 #0 ContextMenuDialogFragment}

**Comment by dskato** [comment]
Please this, question is not closed i need a solution
