### ISSUE TITLE
how can I add padding to icon or reduce icon size?

### ISSUE THREAD

**Issue by sagarrishabh** [Yalantis/Context-Menu.Android#51]

**Comment by warko-san** [comment]
Hi, @sagarrishabh! You can reduce icon size by applying `setActionBarSize(your_dimension)`

**Comment by PenzK** [comment]
If you need to chage ContextMenu Icon params try to edit Utils.getItemImageButton(...) and Utils.getImageWrapper(...)

**Comment by innoflash** [comment]
I suppose this answer is obsolete now, I cant seem to locate that `Utils` class.

How do you change the padding with the current release?
