### ISSUE TITLE
Expandable listview

### ISSUE THREAD

**Issue by sagarika-halya** [Yalantis/Context-Menu.Android#52]
Hi ,

Thanks for providing nice library...Can we implement expandable listview for this menu??

For example if we click on messages option can we display the sub items like inbox,outbox and send message below the message option.

**Comment by warko-san** [comment]
Hi, @sagarika-halya! Thank you for reporting this issue. 
Now, it's impossible to attach expandable list view as `MenuObject`, because the last one is designed in the way to hold just title and some resources to make it look better.
