### ISSUE TITLE
how can i change position dialog in left side ?

### ISSUE THREAD

**Issue by joShinichi** [Yalantis/Context-Menu.Android#53]
hi...i used your library and that was awesome...
but my question is, can i customize the dialog position to the left side ?

thanks and best regards....

**Comment by warko-san** [comment]
Hi, @joShinichi! Thank you for reporting this issue. 
Now, this lib is designed in the way to be displayed on the right/end side of the screen. And there is no ability to customize its position.

**Comment by johny-g3** [comment]
I got it, all you need is change these files

- fragment_menu.xml
`<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/menu_fragment_background"
    android:fillViewport="true">

    <RelativeLayout
        android:id="@+id/root"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <LinearLayout
            android:id="@+id/wrapper_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/text_wrapper_right_margin"
            android:layout_marginStart="@dimen/text_wrapper_right_margin"
            android:layout_toEndOf="@+id/wrapper_buttons"
            android:layout_toRightOf="@+id/wrapper_buttons"
            android:gravity="start"
            android:orientation="vertical" />

        <LinearLayout
            android:id="@+id/wrapper_buttons"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:orientation="vertical" />
    </RelativeLayout>
</ScrollView>`

- MenuAdapter.java change resetSideAnimation(View view)

`private void resetSideAnimation(View view) {
        if (!mIsMenuOpen) {
            ViewHelper.setRotation(view, 0);
            ViewHelper.setRotationY(view, -90);
            ViewHelper.setRotationX(view, 0);
        }
        ViewHelper.setPivotX(view, 0);
        ViewHelper.setPivotY(view, mMenuItemSize / 2);
    }`

- AnimatorUtils.java change rotationCloseToRight(View v) and rotationOpenFromRight(View v)

`public static ObjectAnimator rotationCloseToLeft(View v) {
        return ObjectAnimator.ofFloat(v, "rotationY", 0, 90);
    }

    public static ObjectAnimator rotationOpenFromLeft(View v) {
        return ObjectAnimator.ofFloat(v, "rotationY", 90, 0);
    }`

**Comment by johny-g3** [comment]
And change the dimens file

<dimen name="text_wrapper_right_margin">8dp</dimen>

**Comment by quensh93** [comment]
just add this in Manifest 

android:supportsRtl="false"  -> open from right
android:supportsRtl="true" -> open from left

**Comment by PenzK** [comment]
Gravity added, check readme
