### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by sagarrishabh** [Yalantis/Context-Menu.Android#55]
How can I show this context menu while having full screen layout ?

**Comment by warko-san** [comment]
Hi, @sagarrishabh! You can show this context menu by any action you want. Invoking it from toolbar is not necessary.

**Comment by sagarrishabh** [comment]
I mean when I show this menu the statusbar reappear. Is there any way to disable statusbar?

**Comment by PenzK** [comment]
Hi, @sagarrishabh you can try to edit lib styles for this
