### ISSUE TITLE
i am using this library but it throws me java.lang.NoClassDefFoundError exception Any idea! may be the issue is here Failed resolving 'Lcom/yalantis/contextmenu/lib/interfaces/OnMenuItemClickListener; 

### ISSUE THREAD

**Issue by BasitQadri** [Yalantis/Context-Menu.Android#57]

**Comment by PenzK** [comment]
> 'Lcom/yalantis/contextmenu/lib/interfaces/OnMenuItemClickListener;

Maybe 'L is issue?
Provide more logs please
http://stackoverflow.com/questions/17973970/how-to-solve-java-lang-noclassdeffounderror

**Comment by BasitQadri** [comment]
problem solved
