### ISSUE TITLE
customize

### ISSUE THREAD

**Issue by gsus24** [Yalantis/Context-Menu.Android#6]
Thanks for your great library. I wish to implement in my app.
I didn´t find on the fly a way to setBackgroundColor instead of white a custom one.
And Theme also changed my transulent StatusBar.

Thanks for attention 
Cheers

**Comment by alexzaitsev** [comment]
Will be implemented in the next release. Thank you for participation.

**Comment by alexzaitsev** [comment]
Done. README is updated.
