### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by MS893** [Yalantis/Context-Menu.Android#61]
Hi, I have this crash report :

**Exception java.lang.IncompatibleClassChangeError: Class 'java.lang.String' does not implement interface 'java.util.List' in call to 'java.lang.Object java.util.List.get(int)' (declaration of 'com.yalantis.contextmenu.lib.MenuAdapter' appears in /data/app/com.pomfy-1/split_lib_dependencies_apk.apk)**

com.yalantis.contextmenu.lib.MenuAdapter.setViews (MenuAdapter.java:72)
com.yalantis.contextmenu.lib.MenuAdapter.<init> (MenuAdapter.java:49)
com.yalantis.contextmenu.lib.ContextMenuDialogFragment.initDropDownMenuAdapter (ContextMenuDialogFragment.java:130)
com.yalantis.contextmenu.lib.ContextMenuDialogFragment.onCreateView (ContextMenuDialogFragment.java:102)
android.support.v4.app.Fragment.performCreateView (Fragment.java:2192)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1299)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1528)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1595)
android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:758)
android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2363)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2149)
android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps (FragmentManager.java:2103)
android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2013)
android.support.v4.app.FragmentManagerImpl$1.run (FragmentManager.java:710)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6290)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

**Comment by p1nkydev** [comment]
@MS893 Can you provide steps to reproduce?

**Comment by MS893** [comment]
No sorry, one user of my app get this error, I don't know how...

**Comment by p1nkydev** [comment]
Hello, unfortunately I can't help you than, because no one else reported
this crash anymore.

чт, 28 февр. 2019 г. в 14:31, Christian <notifications@github.com>:
