### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by artests87** [Yalantis/Context-Menu.Android#62]
Hello!
I found a bug.
After I closed context-menu (a button for close) and before menu will close if I tap on the home button- the application crash.
This problem on the context-menu side.
Thanks!

**Comment by kstanislav** [comment]
Hello.
Check out latest version. This problem was fixed here #72 
Thank you, good luck.

**Comment by artests87** [comment]
Hello.
Thank you
