### ISSUE TITLE
statusbar

### ISSUE THREAD

**Issue by amin9565** [Yalantis/Context-Menu.Android#69]
hello thanks for excellent lib 
i use your lib in my application and i want hide status bar .(when click on option button shown status bar )
what do i do ?
thanks a lot

**Comment by p1nkydev** [comment]
Hello, @amin9565 basically, when you show context menu you can also call method which will be show/hide your status bar. Here an answer on stackoverflow how to implement it. https://stackoverflow.com/questions/8273186/android-show-hide-status-bar-power-bar
