### ISSUE TITLE
how to change the size of icons its too small.....

### ISSUE THREAD

**Issue by AmirSuwal** [Yalantis/Context-Menu.Android#71]

**Comment by kstanislav** [comment]
Hello, @AmirSuwal . 
Icons you used in Context-Menu is up to you. 

You can set your own icons and resources:
`item.setResource(...)  
    item.setBitmap(...)  
    item.setDrawable(...)  
    item.setColor(...)`

Also you can scale it using ScaleType:
`item.setScaleType(ScaleType.FIT_XY)`

Give a look through [README.md](https://github.com/Yalantis/Context-Menu.Android/blob/master/README.md) for more.
