### ISSUE TITLE
How can I make it sliding from the side?

### ISSUE THREAD

**Issue by vadhmln** [Yalantis/Context-Menu.Android#76]
Hello, everyone! Thank you for your amazing job!
I want the contextMenu has the ability to slide from the side.
I know there is the Side-Menu option but there is no opportunity to set Text for the menu items.
Can I make my own drawer and set the Context-Menu there?
So, any suggestions.

**Comment by PenzK** [comment]
for now there is only option to show menu from left side and from right
You can fork and modify layout of container and animations
